logging:
  level:
    org.springframework.cloud: TRACE

spring:
  datasource:
    hikari:
      # TODO setting auto-commit: true will work around the problem but is that the right idea?
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
