logging:
  level:
    org.springframework.cloud: TRACE

spring:
  datasource:
    hikari:
      # TODO setting default auto-commit: true solves the problem 
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
